-- Decompiled with CoDLUIDecompiler by JariK

require("lua.Shared.LuaEnums")
require("lua.Shared.LuaUtils")
local registerVal1 = {}
local registerVal2 = {}
registerVal2.id = 0.000000
registerVal2.name = "Main"
registerVal2.title = ""
registerVal2.kicker = ""
registerVal2.room = "room1"
registerVal2.isPrivate = false
registerVal2.isGame = false
registerVal2.isAdvertised = false
registerVal2.maxClients = 0.000000
registerVal2.maxLocalClients = 0.000000
registerVal2.maxLocalClientsNetwork = 0.000000
registerVal2.mainMode = Enum.LobbyMainMode.LOBBY_MAINMODE_INVALID
registerVal2.networkMode = Enum.LobbyNetworkMode.LOBBY_NETWORKMODE_INVALID
registerVal2.lobbyType = Enum.LobbyType.LOBBY_TYPE_INVALID
registerVal2.lobbyMode = Enum.LobbyMode.LOBBY_MODE_INVALID
registerVal2.eGameModes = Enum.eGameModes.MODE_GAME_INVALID
registerVal2.lobbyTimerType = LuaEnums.TIMER_TYPE.INVALID
registerVal2.menuMusic = "titlescreen"
registerVal2.joinPartyPrivacyCheck = false
registerVal1.UI_MAIN = registerVal2
registerVal2 = {}
registerVal2.id = 1.000000
registerVal2.name = "ModeSelect"
registerVal2.title = ""
registerVal2.kicker = ""
registerVal2.room = "auto"
registerVal2.isPrivate = true
registerVal2.isGame = false
registerVal2.isAdvertised = false
registerVal2.maxClients = 18.000000
registerVal2.maxLocalClients = 4.000000
registerVal2.maxLocalClientsNetwork = 2.000000
registerVal2.mainMode = Enum.LobbyMainMode.LOBBY_MAINMODE_INVALID
registerVal2.networkMode = Enum.LobbyNetworkMode.LOBBY_NETWORKMODE_INVALID
registerVal2.lobbyType = Enum.LobbyType.LOBBY_TYPE_PRIVATE
registerVal2.lobbyMode = Enum.LobbyMode.LOBBY_MODE_INVALID
registerVal2.eGameModes = Enum.eGameModes.MODE_GAME_INVALID
registerVal2.lobbyTimerType = LuaEnums.TIMER_TYPE.INVALID
registerVal2.menuMusic = "titlescreen"
registerVal2.joinPartyPrivacyCheck = true
registerVal1.UI_MODESELECT = registerVal2
registerVal2 = {}
registerVal2.id = 100.000000
registerVal2.name = "CPLobbyOnline"
registerVal2.title = "MENU_CAMPAIGN_CAPS"
registerVal2.kicker = "MENU_CAMPAIGN"
registerVal2.room = "cp"
registerVal2.isPrivate = true
registerVal2.isGame = true
registerVal2.isAdvertised = false
registerVal2.maxClients = 4.000000
registerVal2.maxLocalClients = 2.000000
registerVal2.maxLocalClientsNetwork = 2.000000
registerVal2.mainMode = Enum.LobbyMainMode.LOBBY_MAINMODE_CP
registerVal2.networkMode = Enum.LobbyNetworkMode.LOBBY_NETWORKMODE_LIVE
registerVal2.lobbyType = Enum.LobbyType.LOBBY_TYPE_GAME
registerVal2.lobbyMode = Enum.LobbyMode.LOBBY_MODE_CUSTOM
registerVal2.eGameModes = Enum.eGameModes.MODE_GAME_MATCHMAKING_MANUAL
registerVal2.lobbyTimerType = LuaEnums.TIMER_TYPE.NONE
registerVal2.menuMusic = "cp_frontend"
registerVal2.joinPartyPrivacyCheck = true
registerVal1.UI_CPLOBBYONLINE = registerVal2
registerVal2 = {}
registerVal2.id = 101.000000
registerVal2.name = "CPLobbyOnlinePublicGame"
registerVal2.title = "MENU_CAMPAIGN_CAPS"
registerVal2.kicker = "MPUI_PUBLIC_MATCH_LOBBY"
registerVal2.room = "cp"
registerVal2.isPrivate = true
registerVal2.isGame = true
registerVal2.isAdvertised = true
registerVal2.maxClients = 4.000000
registerVal2.maxLocalClients = 2.000000
registerVal2.maxLocalClientsNetwork = 2.000000
registerVal2.mainMode = Enum.LobbyMainMode.LOBBY_MAINMODE_CP
registerVal2.networkMode = Enum.LobbyNetworkMode.LOBBY_NETWORKMODE_LIVE
registerVal2.lobbyType = Enum.LobbyType.LOBBY_TYPE_GAME
registerVal2.lobbyMode = Enum.LobbyMode.LOBBY_MODE_PUBLIC
registerVal2.eGameModes = Enum.eGameModes.MODE_GAME_MATCHMAKING_PLAYLIST
registerVal2.lobbyTimerType = LuaEnums.TIMER_TYPE.AUTO_CP
registerVal2.menuMusic = "cp_frontend"
registerVal2.joinPartyPrivacyCheck = false
registerVal1.UI_CPLOBBYONLINEPUBLICGAME = registerVal2
registerVal2 = {}
registerVal2.id = 102.000000
registerVal2.name = "CPLobbyOnlineCustomGame"
registerVal2.title = "MENU_REPLAY_MISSION_CAPS"
registerVal2.kicker = "MENU_FILESHARE_CUSTOMGAMES"
registerVal2.room = "cp"
registerVal2.isPrivate = true
registerVal2.isGame = true
registerVal2.isAdvertised = false
registerVal2.maxClients = 4.000000
registerVal2.maxLocalClients = 2.000000
registerVal2.maxLocalClientsNetwork = 2.000000
registerVal2.mainMode = Enum.LobbyMainMode.LOBBY_MAINMODE_CP
registerVal2.networkMode = Enum.LobbyNetworkMode.LOBBY_NETWORKMODE_LIVE
registerVal2.lobbyType = Enum.LobbyType.LOBBY_TYPE_GAME
registerVal2.lobbyMode = Enum.LobbyMode.LOBBY_MODE_CUSTOM
registerVal2.eGameModes = Enum.eGameModes.MODE_GAME_MATCHMAKING_MANUAL
registerVal2.lobbyTimerType = LuaEnums.TIMER_TYPE.MANUAL_CP
registerVal2.menuMusic = "cp_frontend"
registerVal2.joinPartyPrivacyCheck = true
registerVal1.UI_CPLOBBYONLINECUSTOMGAME = registerVal2
registerVal2 = {}
registerVal2.id = 110.000000
registerVal2.name = "CPLobbyLANGame"
registerVal2.title = "MENU_CAMPAIGN_CAPS"
registerVal2.kicker = ""
registerVal2.room = "cp"
registerVal2.isPrivate = true
registerVal2.isGame = true
registerVal2.isAdvertised = false
registerVal2.maxClients = 4.000000
registerVal2.maxLocalClients = 2.000000
registerVal2.maxLocalClientsNetwork = 2.000000
registerVal2.mainMode = Enum.LobbyMainMode.LOBBY_MAINMODE_CP
registerVal2.networkMode = Enum.LobbyNetworkMode.LOBBY_NETWORKMODE_LAN
registerVal2.lobbyType = Enum.LobbyType.LOBBY_TYPE_GAME
registerVal2.lobbyMode = Enum.LobbyMode.LOBBY_MODE_CUSTOM
registerVal2.eGameModes = Enum.eGameModes.MODE_GAME_INVALID
registerVal2.lobbyTimerType = LuaEnums.TIMER_TYPE.MANUAL_CP
registerVal2.menuMusic = "cp_frontend"
registerVal2.joinPartyPrivacyCheck = false
registerVal1.UI_CPLOBBYLANGAME = registerVal2
registerVal2 = {}
registerVal2.id = 111.000000
registerVal2.name = "CPLobbyLANCustomGame"
registerVal2.title = "MENU_REPLAY_MISSION_CAPS"
registerVal2.kicker = ""
registerVal2.room = "cp"
registerVal2.isPrivate = true
registerVal2.isGame = true
registerVal2.isAdvertised = false
registerVal2.maxClients = 4.000000
registerVal2.maxLocalClients = 2.000000
registerVal2.maxLocalClientsNetwork = 2.000000
registerVal2.mainMode = Enum.LobbyMainMode.LOBBY_MAINMODE_CP
registerVal2.networkMode = Enum.LobbyNetworkMode.LOBBY_NETWORKMODE_LAN
registerVal2.lobbyType = Enum.LobbyType.LOBBY_TYPE_GAME
registerVal2.lobbyMode = Enum.LobbyMode.LOBBY_MODE_CUSTOM
registerVal2.eGameModes = Enum.eGameModes.MODE_GAME_INVALID
registerVal2.lobbyTimerType = LuaEnums.TIMER_TYPE.MANUAL_CP
registerVal2.menuMusic = "cp_frontend"
registerVal2.joinPartyPrivacyCheck = false
registerVal1.UI_CPLOBBYLANCUSTOMGAME = registerVal2
registerVal2 = {}
registerVal2.id = 200.000000
registerVal2.name = "CP2LobbyOnline"
registerVal2.title = "MENU_SINGLEPLAYER_NIGHTMARES_CAPS"
registerVal2.kicker = ""
registerVal2.room = "cpzm"
registerVal2.isPrivate = true
registerVal2.isGame = true
registerVal2.isAdvertised = false
registerVal2.maxClients = 4.000000
registerVal2.maxLocalClients = 2.000000
registerVal2.maxLocalClientsNetwork = 2.000000
registerVal2.mainMode = Enum.LobbyMainMode.LOBBY_MAINMODE_CP
registerVal2.networkMode = Enum.LobbyNetworkMode.LOBBY_NETWORKMODE_LIVE
registerVal2.lobbyType = Enum.LobbyType.LOBBY_TYPE_GAME
registerVal2.lobbyMode = Enum.LobbyMode.LOBBY_MODE_CUSTOM
registerVal2.eGameModes = Enum.eGameModes.MODE_GAME_MATCHMAKING_MANUAL
registerVal2.lobbyTimerType = LuaEnums.TIMER_TYPE.NONE
registerVal2.menuMusic = "zm_cp_frontend"
registerVal2.joinPartyPrivacyCheck = true
registerVal1.UI_CP2LOBBYONLINE = registerVal2
registerVal2 = {}
registerVal2.id = 201.000000
registerVal2.name = "CP2LobbyOnlinePublicGame"
registerVal2.title = "MENU_SINGLEPLAYER_NIGHTMARES_CAPS"
registerVal2.kicker = "MPUI_PUBLIC_MATCH_LOBBY"
registerVal2.room = "cpzm"
registerVal2.isPrivate = true
registerVal2.isGame = true
registerVal2.isAdvertised = true
registerVal2.maxClients = 4.000000
registerVal2.maxLocalClients = 2.000000
registerVal2.maxLocalClientsNetwork = 2.000000
registerVal2.mainMode = Enum.LobbyMainMode.LOBBY_MAINMODE_CP
registerVal2.networkMode = Enum.LobbyNetworkMode.LOBBY_NETWORKMODE_LIVE
registerVal2.lobbyType = Enum.LobbyType.LOBBY_TYPE_GAME
registerVal2.lobbyMode = Enum.LobbyMode.LOBBY_MODE_PUBLIC
registerVal2.eGameModes = Enum.eGameModes.MODE_GAME_MATCHMAKING_PLAYLIST
registerVal2.lobbyTimerType = LuaEnums.TIMER_TYPE.AUTO_CP
registerVal2.menuMusic = "zm_cp_frontend"
registerVal2.joinPartyPrivacyCheck = false
registerVal1.UI_CP2LOBBYONLINEPUBLICGAME = registerVal2
registerVal2 = {}
registerVal2.id = 202.000000
registerVal2.name = "CP2LobbyOnlineCustomGame"
registerVal2.title = "MENU_CUSTOMGAMES_CAPS"
registerVal2.kicker = "MENU_FILESHARE_CUSTOMGAMES"
registerVal2.room = "cpzm"
registerVal2.isPrivate = true
registerVal2.isGame = true
registerVal2.isAdvertised = false
registerVal2.maxClients = 4.000000
registerVal2.maxLocalClients = 2.000000
registerVal2.maxLocalClientsNetwork = 2.000000
registerVal2.mainMode = Enum.LobbyMainMode.LOBBY_MAINMODE_CP
registerVal2.networkMode = Enum.LobbyNetworkMode.LOBBY_NETWORKMODE_LIVE
registerVal2.lobbyType = Enum.LobbyType.LOBBY_TYPE_GAME
registerVal2.lobbyMode = Enum.LobbyMode.LOBBY_MODE_CUSTOM
registerVal2.eGameModes = Enum.eGameModes.MODE_GAME_MATCHMAKING_MANUAL
registerVal2.lobbyTimerType = LuaEnums.TIMER_TYPE.MANUAL_CP
registerVal2.menuMusic = "zm_cp_frontend"
registerVal2.joinPartyPrivacyCheck = true
registerVal1.UI_CP2LOBBYONLINECUSTOMGAME = registerVal2
registerVal2 = {}
registerVal2.id = 210.000000
registerVal2.name = "CP2LobbyLANGame"
registerVal2.title = "MENU_SINGLEPLAYER_NIGHTMARES_CAPS"
registerVal2.kicker = ""
registerVal2.room = "cpzm"
registerVal2.isPrivate = true
registerVal2.isGame = true
registerVal2.isAdvertised = false
registerVal2.maxClients = 4.000000
registerVal2.maxLocalClients = 2.000000
registerVal2.maxLocalClientsNetwork = 2.000000
registerVal2.mainMode = Enum.LobbyMainMode.LOBBY_MAINMODE_CP
registerVal2.networkMode = Enum.LobbyNetworkMode.LOBBY_NETWORKMODE_LAN
registerVal2.lobbyType = Enum.LobbyType.LOBBY_TYPE_GAME
registerVal2.lobbyMode = Enum.LobbyMode.LOBBY_MODE_CUSTOM
registerVal2.eGameModes = Enum.eGameModes.MODE_GAME_INVALID
registerVal2.lobbyTimerType = LuaEnums.TIMER_TYPE.MANUAL_CP
registerVal2.menuMusic = "zm_cp_frontend"
registerVal2.joinPartyPrivacyCheck = false
registerVal1.UI_CP2LOBBYLANGAME = registerVal2
registerVal2 = {}
registerVal2.id = 211.000000
registerVal2.name = "CP2LobbyLANCustomGame"
registerVal2.title = "MENU_REPLAY_MISSION_CAPS"
registerVal2.kicker = ""
registerVal2.room = "cpzm"
registerVal2.isPrivate = true
registerVal2.isGame = true
registerVal2.isAdvertised = false
registerVal2.maxClients = 4.000000
registerVal2.maxLocalClients = 2.000000
registerVal2.maxLocalClientsNetwork = 2.000000
registerVal2.mainMode = Enum.LobbyMainMode.LOBBY_MAINMODE_CP
registerVal2.networkMode = Enum.LobbyNetworkMode.LOBBY_NETWORKMODE_LAN
registerVal2.lobbyType = Enum.LobbyType.LOBBY_TYPE_GAME
registerVal2.lobbyMode = Enum.LobbyMode.LOBBY_MODE_CUSTOM
registerVal2.eGameModes = Enum.eGameModes.MODE_GAME_INVALID
registerVal2.lobbyTimerType = LuaEnums.TIMER_TYPE.MANUAL_CP
registerVal2.menuMusic = "zm_cp_frontend"
registerVal2.joinPartyPrivacyCheck = false
registerVal1.UI_CP2LOBBYLANCUSTOMGAME = registerVal2
registerVal2 = {}
registerVal2.id = 300.000000
registerVal2.name = "MPLobbyMain"
registerVal2.title = "MENU_MULTIPLAYER_CAPS"
registerVal2.kicker = "MENU_MULTIPLAYER"
registerVal2.room = "mp_online"
registerVal2.isPrivate = true
registerVal2.isGame = false
registerVal2.isAdvertised = false
registerVal2.maxClients = 18.000000
registerVal2.maxLocalClients = 2.000000
registerVal2.maxLocalClientsNetwork = 2.000000
registerVal2.mainMode = Enum.LobbyMainMode.LOBBY_MAINMODE_MP
registerVal2.networkMode = Enum.LobbyNetworkMode.LOBBY_NETWORKMODE_LIVE
registerVal2.lobbyType = Enum.LobbyType.LOBBY_TYPE_PRIVATE
registerVal2.lobbyMode = Enum.LobbyMode.LOBBY_MODE_INVALID
registerVal2.eGameModes = Enum.eGameModes.MODE_GAME_INVALID
registerVal2.lobbyTimerType = LuaEnums.TIMER_TYPE.INVALID
registerVal2.menuMusic = "mp_frontend"
registerVal2.joinPartyPrivacyCheck = true
registerVal1.UI_MPLOBBYMAIN = registerVal2
registerVal2 = {}
registerVal2.id = 301.000000
registerVal2.name = "MPLobbyOnline"
registerVal2.title = "MENU_MATCHMAKING_CAPS"
registerVal2.kicker = "MPUI_PUBLIC_MATCH_LOBBY"
registerVal2.room = "mp_online"
registerVal2.isPrivate = true
registerVal2.isGame = false
registerVal2.isAdvertised = false
registerVal2.maxClients = 18.000000
registerVal2.maxLocalClients = 2.000000
registerVal2.maxLocalClientsNetwork = 2.000000
registerVal2.mainMode = Enum.LobbyMainMode.LOBBY_MAINMODE_MP
registerVal2.networkMode = Enum.LobbyNetworkMode.LOBBY_NETWORKMODE_LIVE
registerVal2.lobbyType = Enum.LobbyType.LOBBY_TYPE_PRIVATE
registerVal2.lobbyMode = Enum.LobbyMode.LOBBY_MODE_PUBLIC
registerVal2.eGameModes = Enum.eGameModes.MODE_GAME_INVALID
registerVal2.lobbyTimerType = LuaEnums.TIMER_TYPE.INVALID
registerVal2.menuMusic = "mp_frontend"
registerVal2.joinPartyPrivacyCheck = true
registerVal1.UI_MPLOBBYONLINE = registerVal2
registerVal2 = {}
registerVal2.id = 310.000000
registerVal2.name = "MPLobbyOnlinePublicGame"
registerVal2.title = "MENU_MULTIPLAYER_CAPS"
registerVal2.kicker = "MPUI_PUBLIC_MATCH_LOBBY"
registerVal2.room = "mp_online"
registerVal2.isPrivate = true
registerVal2.isGame = true
registerVal2.isAdvertised = true
registerVal2.maxClients = 18.000000
registerVal2.maxLocalClients = 2.000000
registerVal2.maxLocalClientsNetwork = 2.000000
registerVal2.mainMode = Enum.LobbyMainMode.LOBBY_MAINMODE_MP
registerVal2.networkMode = Enum.LobbyNetworkMode.LOBBY_NETWORKMODE_LIVE
registerVal2.lobbyType = Enum.LobbyType.LOBBY_TYPE_GAME
registerVal2.lobbyMode = Enum.LobbyMode.LOBBY_MODE_PUBLIC
registerVal2.eGameModes = Enum.eGameModes.MODE_GAME_MATCHMAKING_PLAYLIST
registerVal2.lobbyTimerType = LuaEnums.TIMER_TYPE.AUTO_MP
registerVal2.menuMusic = "mp_frontend"
registerVal2.joinPartyPrivacyCheck = false
registerVal1.UI_MPLOBBYONLINEPUBLICGAME = registerVal2
registerVal2 = {}
registerVal2.id = 320.000000
registerVal2.name = "MPLobbyOnlineModGame"
registerVal2.title = "MENU_CUSTOMGAMES_CAPS"
registerVal2.kicker = ""
registerVal2.room = "mp_custom"
registerVal2.isPrivate = true
registerVal2.isGame = true
registerVal2.isAdvertised = true
registerVal2.maxClients = 18.000000
registerVal2.maxLocalClients = 2.000000
registerVal2.maxLocalClientsNetwork = 2.000000
registerVal2.mainMode = Enum.LobbyMainMode.LOBBY_MAINMODE_MP
registerVal2.networkMode = Enum.LobbyNetworkMode.LOBBY_NETWORKMODE_LIVE
registerVal2.lobbyType = Enum.LobbyType.LOBBY_TYPE_GAME
registerVal2.lobbyMode = Enum.LobbyMode.LOBBY_MODE_CUSTOM
registerVal2.eGameModes = Enum.eGameModes.MODE_GAME_MANUAL_PLAYLIST
registerVal2.lobbyTimerType = LuaEnums.TIMER_TYPE.AUTO_MP
registerVal2.menuMusic = "mp_frontend"
registerVal2.joinPartyPrivacyCheck = false
registerVal1.UI_MPLOBBYONLINEMODGAME = registerVal2
registerVal2 = {}
registerVal2.id = 330.000000
registerVal2.name = "MPLobbyOnlineCustomGame"
registerVal2.title = "MENU_CUSTOMGAMES_CAPS"
registerVal2.kicker = "MENU_FILESHARE_CUSTOMGAMES"
registerVal2.room = "mp_custom"
registerVal2.isPrivate = true
registerVal2.isGame = true
registerVal2.isAdvertised = false
registerVal2.maxClients = 18.000000
registerVal2.maxLocalClients = 2.000000
registerVal2.maxLocalClientsNetwork = 2.000000
registerVal2.mainMode = Enum.LobbyMainMode.LOBBY_MAINMODE_MP
registerVal2.networkMode = Enum.LobbyNetworkMode.LOBBY_NETWORKMODE_LIVE
registerVal2.lobbyType = Enum.LobbyType.LOBBY_TYPE_GAME
registerVal2.lobbyMode = Enum.LobbyMode.LOBBY_MODE_CUSTOM
registerVal2.eGameModes = Enum.eGameModes.MODE_GAME_MATCHMAKING_MANUAL
registerVal2.lobbyTimerType = LuaEnums.TIMER_TYPE.MANUAL
registerVal2.menuMusic = "mp_frontend"
registerVal2.joinPartyPrivacyCheck = true
registerVal1.UI_MPLOBBYONLINECUSTOMGAME = registerVal2
registerVal2 = {}
registerVal2.id = 340.000000
registerVal2.name = "MPLobbyOnlineTheater"
registerVal2.title = "MENU_THEATER_CAPS"
registerVal2.kicker = ""
registerVal2.room = "mp_theater"
registerVal2.isPrivate = true
registerVal2.isGame = true
registerVal2.isAdvertised = false
registerVal2.maxClients = 1.000000
registerVal2.maxLocalClients = 1.000000
registerVal2.maxLocalClientsNetwork = 1.000000
registerVal2.mainMode = Enum.LobbyMainMode.LOBBY_MAINMODE_MP
registerVal2.networkMode = Enum.LobbyNetworkMode.LOBBY_NETWORKMODE_LIVE
registerVal2.lobbyType = Enum.LobbyType.LOBBY_TYPE_GAME
registerVal2.lobbyMode = Enum.LobbyMode.LOBBY_MODE_THEATER
registerVal2.eGameModes = Enum.eGameModes.MODE_GAME_THEATER
registerVal2.lobbyTimerType = LuaEnums.TIMER_TYPE.THEATER
registerVal2.menuMusic = "mp_frontend"
registerVal2.joinPartyPrivacyCheck = true
registerVal1.UI_MPLOBBYONLINETHEATER = registerVal2
registerVal2 = {}
registerVal2.id = 390.000000
registerVal2.name = "MPLobbyLANGame"
registerVal2.title = "MENU_MULTIPLAYER_CAPS"
registerVal2.kicker = "MENU_MULTIPLAYER"
registerVal2.room = "mp"
registerVal2.isPrivate = true
registerVal2.isGame = true
registerVal2.isAdvertised = false
registerVal2.maxClients = 18.000000
registerVal2.maxLocalClients = 4.000000
registerVal2.maxLocalClientsNetwork = 2.000000
registerVal2.mainMode = Enum.LobbyMainMode.LOBBY_MAINMODE_MP
registerVal2.networkMode = Enum.LobbyNetworkMode.LOBBY_NETWORKMODE_LAN
registerVal2.lobbyType = Enum.LobbyType.LOBBY_TYPE_GAME
registerVal2.lobbyMode = Enum.LobbyMode.LOBBY_MODE_CUSTOM
registerVal2.eGameModes = Enum.eGameModes.MODE_GAME_MATCHMAKING_MANUAL
registerVal2.lobbyTimerType = LuaEnums.TIMER_TYPE.MANUAL
registerVal2.menuMusic = "mp_frontend"
registerVal2.joinPartyPrivacyCheck = false
registerVal1.UI_MPLOBBYLANGAME = registerVal2
registerVal2 = {}
registerVal2.id = 350.000000
registerVal2.name = "MPLobbyOnlineArena"
registerVal2.title = "MENU_ARENA_CAPS"
registerVal2.kicker = "MENU_ARENA_CAPS"
registerVal2.room = "mp_arena"
registerVal2.isPrivate = true
registerVal2.isGame = false
registerVal2.isAdvertised = false
registerVal2.maxClients = 18.000000
registerVal2.maxLocalClients = 1.000000
registerVal2.maxLocalClientsNetwork = 1.000000
registerVal2.mainMode = Enum.LobbyMainMode.LOBBY_MAINMODE_MP
registerVal2.networkmode = Enum.LobbyNetworkMode.LOBBY_NETWORKMODE_LIVE
registerVal2.lobbyType = Enum.LobbyType.LOBBY_TYPE_PRIVATE
registerVal2.lobbyMode = Enum.LobbyMode.LOBBY_MODE_ARENA
registerVal2.eGameModes = Enum.eGameModes.MODE_GAME_LEAGUE
registerVal2.lobbyTimerType = LuaEnums.TIMER_TYPE.INVALID
registerVal2.menuMusic = "mp_frontend"
registerVal2.joinPartyPrivacyCheck = true
registerVal1.UI_MPLOBBYONLINEARENA = registerVal2
registerVal2 = {}
registerVal2.id = 351.000000
registerVal2.name = "MPLobbyOnlineArenaGame"
registerVal2.title = "MENU_ARENA_CAPS"
registerVal2.kicker = "MENU_ARENA_CAPS"
registerVal2.room = "mp_arena"
registerVal2.isPrivate = true
registerVal2.isGame = true
registerVal2.isAdvertised = true
registerVal2.maxClients = 18.000000
registerVal2.maxLocalClients = 1.000000
registerVal2.maxLocalClientsNetwork = 1.000000
registerVal2.mainMode = Enum.LobbyMainMode.LOBBY_MAINMODE_MP
registerVal2.networkMode = Enum.LobbyNetworkMode.LOBBY_NETWORKMODE_LIVE
registerVal2.lobbyType = Enum.LobbyType.LOBBY_TYPE_GAME
registerVal2.lobbyMode = Enum.LobbyMode.LOBBY_MODE_ARENA
registerVal2.eGameModes = Enum.eGameModes.MODE_GAME_LEAGUE
registerVal2.lobbyTimerType = LuaEnums.TIMER_TYPE.AUTO_MP
registerVal2.menuMusic = "mp_frontend"
registerVal2.joinPartyPrivacyCheck = true
registerVal1.UI_MPLOBBYONLINEARENAGAME = registerVal2
registerVal2 = {}
registerVal2.id = 500.000000
registerVal2.name = "FRLobbyOnlineGame"
registerVal2.title = "MENU_FREERUN_CAPS"
registerVal2.kicker = ""
registerVal2.room = "mp_freerun"
registerVal2.isPrivate = true
registerVal2.isGame = true
registerVal2.isAdvertised = false
registerVal2.maxClients = 1.000000
registerVal2.maxLocalClients = 1.000000
registerVal2.maxLocalClientsNetwork = 1.000000
registerVal2.mainMode = Enum.LobbyMainMode.LOBBY_MAINMODE_MP
registerVal2.networkMode = Enum.LobbyNetworkMode.LOBBY_NETWORKMODE_LIVE
registerVal2.lobbyType = Enum.LobbyType.LOBBY_TYPE_GAME
registerVal2.lobbyMode = Enum.LobbyMode.LOBBY_MODE_FREERUN
registerVal2.eGameModes = Enum.eGameModes.MODE_GAME_FREERUN
registerVal2.lobbyTimerType = LuaEnums.TIMER_TYPE.MANUAL
registerVal2.menuMusic = "free_run"
registerVal2.joinPartyPrivacyCheck = true
registerVal1.UI_FRLOBBYONLINEGAME = registerVal2
registerVal2 = {}
registerVal2.id = 510.000000
registerVal2.name = "FRLobbyLANGame"
registerVal2.title = "MENU_FREERUN_CAPS"
registerVal2.kicker = ""
registerVal2.room = "mp_freerun"
registerVal2.isPrivate = true
registerVal2.isGame = true
registerVal2.isAdvertised = false
registerVal2.maxClients = 1.000000
registerVal2.maxLocalClients = 1.000000
registerVal2.maxLocalClientsNetwork = 1.000000
registerVal2.mainMode = Enum.LobbyMainMode.LOBBY_MAINMODE_MP
registerVal2.networkMode = Enum.LobbyNetworkMode.LOBBY_NETWORKMODE_LAN
registerVal2.lobbyType = Enum.LobbyType.LOBBY_TYPE_GAME
registerVal2.lobbyMode = Enum.LobbyMode.LOBBY_MODE_FREERUN
registerVal2.eGameModes = Enum.eGameModes.MODE_GAME_FREERUN
registerVal2.lobbyTimerType = LuaEnums.TIMER_TYPE.MANUAL
registerVal2.menuMusic = "free_run"
registerVal2.joinPartyPrivacyCheck = false
registerVal1.UI_FRLOBBYLANGAME = registerVal2
registerVal2 = {}
registerVal2.id = 400.000000
registerVal2.name = "ZMLobbyOnline"
registerVal2.title = "MENU_ZOMBIES_CAPS"
registerVal2.kicker = "MENU_ZOMBIES"
registerVal2.room = "zm"
registerVal2.isPrivate = true
registerVal2.isGame = true
registerVal2.isAdvertised = false
registerVal2.maxClients = 4.000000
registerVal2.maxLocalClients = 2.000000
registerVal2.maxLocalClientsNetwork = 2.000000
registerVal2.mainMode = Enum.LobbyMainMode.LOBBY_MAINMODE_ZM
registerVal2.networkMode = Enum.LobbyNetworkMode.LOBBY_NETWORKMODE_LIVE
registerVal2.lobbyType = Enum.LobbyType.LOBBY_TYPE_GAME
registerVal2.lobbyMode = Enum.LobbyMode.LOBBY_MODE_CUSTOM
registerVal2.eGameModes = Enum.eGameModes.MODE_GAME_MATCHMAKING_MANUAL
registerVal2.lobbyTimerType = LuaEnums.TIMER_TYPE.NONE
registerVal2.menuMusic = "zm_frontend"
registerVal2.joinPartyPrivacyCheck = true
registerVal1.UI_ZMLOBBYONLINE = registerVal2
registerVal2 = {}
registerVal2.id = 401.000000
registerVal2.name = "ZMLobbyOnlinePublicGame"
registerVal2.title = "MENU_ZOMBIES_CAPS"
registerVal2.kicker = "MPUI_PUBLIC_MATCH_LOBBY"
registerVal2.room = "zm"
registerVal2.isPrivate = true
registerVal2.isGame = true
registerVal2.isAdvertised = true
registerVal2.maxClients = 4.000000
registerVal2.maxLocalClients = 2.000000
registerVal2.maxLocalClientsNetwork = 2.000000
registerVal2.mainMode = Enum.LobbyMainMode.LOBBY_MAINMODE_ZM
registerVal2.networkMode = Enum.LobbyNetworkMode.LOBBY_NETWORKMODE_LIVE
registerVal2.lobbyType = Enum.LobbyType.LOBBY_TYPE_GAME
registerVal2.lobbyMode = Enum.LobbyMode.LOBBY_MODE_PUBLIC
registerVal2.eGameModes = Enum.eGameModes.MODE_GAME_MATCHMAKING_PLAYLIST
registerVal2.lobbyTimerType = LuaEnums.TIMER_TYPE.AUTO_ZM
registerVal2.menuMusic = "zm_frontend"
registerVal2.joinPartyPrivacyCheck = false
registerVal1.UI_ZMLOBBYONLINEPUBLICGAME = registerVal2
registerVal2 = {}
registerVal2.id = 402.000000
registerVal2.name = "ZMLobbyOnlineCustomGame"
registerVal2.title = "MENU_PRIVATE_GAME_CAPS"
registerVal2.kicker = "MENU_FILESHARE_CUSTOMGAMES"
registerVal2.room = "zm"
registerVal2.isPrivate = true
registerVal2.isGame = true
registerVal2.isAdvertised = false
registerVal2.maxClients = 4.000000
registerVal2.maxLocalClients = 2.000000
registerVal2.maxLocalClientsNetwork = 2.000000
registerVal2.mainMode = Enum.LobbyMainMode.LOBBY_MAINMODE_ZM
registerVal2.networkMode = Enum.LobbyNetworkMode.LOBBY_NETWORKMODE_LIVE
registerVal2.lobbyType = Enum.LobbyType.LOBBY_TYPE_GAME
registerVal2.lobbyMode = Enum.LobbyMode.LOBBY_MODE_CUSTOM
registerVal2.eGameModes = Enum.eGameModes.MODE_GAME_MATCHMAKING_MANUAL
registerVal2.lobbyTimerType = LuaEnums.TIMER_TYPE.MANUAL
registerVal2.menuMusic = "zm_frontend"
registerVal2.joinPartyPrivacyCheck = true
registerVal1.UI_ZMLOBBYONLINECUSTOMGAME = registerVal2
registerVal2 = {}
registerVal2.id = 403.000000
registerVal2.name = "ZMLobbyOnlineTheater"
registerVal2.title = "MENU_THEATER_CAPS"
registerVal2.kicker = ""
registerVal2.room = "zm"
registerVal2.isPrivate = true
registerVal2.isGame = true
registerVal2.isAdvertised = false
registerVal2.maxClients = 1.000000
registerVal2.maxLocalClients = 1.000000
registerVal2.maxLocalClientsNetwork = 1.000000
registerVal2.mainMode = Enum.LobbyMainMode.LOBBY_MAINMODE_ZM
registerVal2.networkMode = Enum.LobbyNetworkMode.LOBBY_NETWORKMODE_LIVE
registerVal2.lobbyType = Enum.LobbyType.LOBBY_TYPE_GAME
registerVal2.lobbyMode = Enum.LobbyMode.LOBBY_MODE_THEATER
registerVal2.eGameModes = Enum.eGameModes.MODE_GAME_THEATER
registerVal2.lobbyTimerType = LuaEnums.TIMER_TYPE.THEATER
registerVal2.menuMusic = "zm_frontend"
registerVal2.joinPartyPrivacyCheck = true
registerVal1.UI_ZMLOBBYONLINETHEATER = registerVal2
registerVal2 = {}
registerVal2.id = 410.000000
registerVal2.name = "ZMLobbyLANGame"
registerVal2.title = "MENU_ZOMBIES_CAPS"
registerVal2.kicker = "MENU_ZOMBIES"
registerVal2.room = "zm"
registerVal2.isPrivate = true
registerVal2.isGame = true
registerVal2.isAdvertised = false
registerVal2.maxClients = 4.000000
registerVal2.maxLocalClients = 4.000000
registerVal2.maxLocalClientsNetwork = 2.000000
registerVal2.mainMode = Enum.LobbyMainMode.LOBBY_MAINMODE_ZM
registerVal2.networkMode = Enum.LobbyNetworkMode.LOBBY_NETWORKMODE_LAN
registerVal2.lobbyType = Enum.LobbyType.LOBBY_TYPE_GAME
registerVal2.lobbyMode = Enum.LobbyMode.LOBBY_MODE_CUSTOM
registerVal2.eGameModes = Enum.eGameModes.MODE_GAME_MATCHMAKING_MANUAL
registerVal2.lobbyTimerType = LuaEnums.TIMER_TYPE.MANUAL
registerVal2.menuMusic = "zm_frontend"
registerVal2.joinPartyPrivacyCheck = false
registerVal1.UI_ZMLOBBYLANGAME = registerVal2
registerVal2 = {}
registerVal2.id = 600.000000
registerVal2.name = "CPDOALobbyOnline"
registerVal2.title = "MENU_DOA2_TITLE"
registerVal2.kicker = ""
registerVal2.room = "doa"
registerVal2.isPrivate = true
registerVal2.isGame = true
registerVal2.isAdvertised = false
registerVal2.maxClients = 4.000000
registerVal2.maxLocalClients = 2.000000
registerVal2.maxLocalClientsNetwork = 2.000000
registerVal2.mainMode = Enum.LobbyMainMode.LOBBY_MAINMODE_CP
registerVal2.networkMode = Enum.LobbyNetworkMode.LOBBY_NETWORKMODE_LIVE
registerVal2.lobbyType = Enum.LobbyType.LOBBY_TYPE_GAME
registerVal2.lobbyMode = Enum.LobbyMode.LOBBY_MODE_CUSTOM
registerVal2.eGameModes = Enum.eGameModes.MODE_GAME_MATCHMAKING_MANUAL
registerVal2.lobbyTimerType = LuaEnums.TIMER_TYPE.MANUAL_CP
registerVal2.menuMusic = "zm_cp_frontend"
registerVal2.joinPartyPrivacyCheck = true
registerVal1.UI_DOALOBBYONLINE = registerVal2
registerVal2 = {}
registerVal2.id = 601.000000
registerVal2.name = "CPDOALobbyOnlinePublicGame"
registerVal2.title = "MENU_DOA2_TITLE"
registerVal2.kicker = "MPUI_PUBLIC_MATCH_LOBBY"
registerVal2.room = "doa"
registerVal2.isPrivate = true
registerVal2.isGame = true
registerVal2.isAdvertised = true
registerVal2.maxClients = 4.000000
registerVal2.maxLocalClients = 2.000000
registerVal2.maxLocalClientsNetwork = 2.000000
registerVal2.mainMode = Enum.LobbyMainMode.LOBBY_MAINMODE_CP
registerVal2.networkMode = Enum.LobbyNetworkMode.LOBBY_NETWORKMODE_LIVE
registerVal2.lobbyType = Enum.LobbyType.LOBBY_TYPE_GAME
registerVal2.lobbyMode = Enum.LobbyMode.LOBBY_MODE_PUBLIC
registerVal2.eGameModes = Enum.eGameModes.MODE_GAME_MATCHMAKING_PLAYLIST
registerVal2.lobbyTimerType = LuaEnums.TIMER_TYPE.AUTO_CP
registerVal2.menuMusic = "zm_cp_frontend"
registerVal2.joinPartyPrivacyCheck = false
registerVal1.UI_DOALOBBYONLINEPUBLICGAME = registerVal2
registerVal2 = {}
registerVal2.id = 610.000000
registerVal2.name = "CPDOALobbyLANGame"
registerVal2.title = "MENU_DOA2_TITLE"
registerVal2.kicker = ""
registerVal2.room = "doa"
registerVal2.isPrivate = true
registerVal2.isGame = true
registerVal2.isAdvertised = false
registerVal2.maxClients = 4.000000
registerVal2.maxLocalClients = 4.000000
registerVal2.maxLocalClientsNetwork = 2.000000
registerVal2.mainMode = Enum.LobbyMainMode.LOBBY_MAINMODE_CP
registerVal2.networkMode = Enum.LobbyNetworkMode.LOBBY_NETWORKMODE_LAN
registerVal2.lobbyType = Enum.LobbyType.LOBBY_TYPE_GAME
registerVal2.lobbyMode = Enum.LobbyMode.LOBBY_MODE_CUSTOM
registerVal2.eGameModes = Enum.eGameModes.MODE_GAME_INVALID
registerVal2.lobbyTimerType = LuaEnums.TIMER_TYPE.MANUAL_CP
registerVal2.menuMusic = "zm_cp_frontend"
registerVal2.joinPartyPrivacyCheck = false
registerVal1.UI_DOALOBBYLANGAME = registerVal2
registerVal2 = {}
registerVal2.id = 611.000000
registerVal2.name = "CPDOALobbyLANCustomGame"
registerVal2.title = "MENU_DOA2_TITLE"
registerVal2.kicker = ""
registerVal2.room = "doa"
registerVal2.isPrivate = true
registerVal2.isGame = true
registerVal2.isAdvertised = false
registerVal2.maxClients = 4.000000
registerVal2.maxLocalClients = 4.000000
registerVal2.maxLocalClientsNetwork = 2.000000
registerVal2.mainMode = Enum.LobbyMainMode.LOBBY_MAINMODE_CP
registerVal2.networkMode = Enum.LobbyNetworkMode.LOBBY_NETWORKMODE_LAN
registerVal2.lobbyType = Enum.LobbyType.LOBBY_TYPE_GAME
registerVal2.lobbyMode = Enum.LobbyMode.LOBBY_MODE_CUSTOM
registerVal2.eGameModes = Enum.eGameModes.MODE_GAME_INVALID
registerVal2.lobbyTimerType = LuaEnums.TIMER_TYPE.MANUAL_CP
registerVal2.menuMusic = "zm_cp_frontend"
registerVal2.joinPartyPrivacyCheck = false
registerVal1.UI_DOALOBBYLANCUSTOMGAME = registerVal2
registerVal1.UI_MAIN.backTarget = nil
registerVal1.UI_MAIN.errTarget = registerVal1.UI_MAIN
registerVal1.UI_MODESELECT.backTarget = registerVal1.UI_MAIN
registerVal1.UI_MODESELECT.errTarget = registerVal1.UI_MODESELECT
registerVal1.UI_CPLOBBYLANGAME.backTarget = registerVal1.UI_MODESELECT
registerVal1.UI_CPLOBBYLANGAME.errTarget = registerVal1.UI_CPLOBBYLANGAME
registerVal1.UI_CPLOBBYLANCUSTOMGAME.backTarget = registerVal1.UI_CPLOBBYLANGAME
registerVal1.UI_CPLOBBYLANCUSTOMGAME.errTarget = registerVal1.UI_CPLOBBYLANGAME
registerVal1.UI_CPLOBBYONLINECUSTOMGAME.backTarget = registerVal1.UI_CPLOBBYONLINE
registerVal1.UI_CPLOBBYONLINECUSTOMGAME.errTarget = registerVal1.UI_CPLOBBYONLINECUSTOMGAME
registerVal1.UI_CPLOBBYONLINE.backTarget = registerVal1.UI_MODESELECT
registerVal1.UI_CPLOBBYONLINE.errTarget = registerVal1.UI_CPLOBBYONLINE
registerVal1.UI_CPLOBBYONLINEPUBLICGAME.backTarget = registerVal1.UI_CPLOBBYONLINE
registerVal1.UI_CPLOBBYONLINEPUBLICGAME.errTarget = registerVal1.UI_CPLOBBYONLINE
registerVal1.UI_CPLOBBYONLINECUSTOMGAME.backTarget = registerVal1.UI_CPLOBBYONLINE
registerVal1.UI_CPLOBBYONLINECUSTOMGAME.errTarget = registerVal1.UI_CPLOBBYONLINECUSTOMGAME
registerVal1.UI_CP2LOBBYLANGAME.backTarget = registerVal1.UI_MODESELECT
registerVal1.UI_CP2LOBBYLANGAME.errTarget = registerVal1.UI_CP2LOBBYLANGAME
registerVal1.UI_CP2LOBBYLANCUSTOMGAME.backTarget = registerVal1.UI_CP2LOBBYLANGAME
registerVal1.UI_CP2LOBBYLANCUSTOMGAME.errTarget = registerVal1.UI_CP2LOBBYLANGAME
registerVal1.UI_CP2LOBBYONLINECUSTOMGAME.backTarget = registerVal1.UI_CP2LOBBYONLINE
registerVal1.UI_CP2LOBBYONLINECUSTOMGAME.errTarget = registerVal1.UI_CP2LOBBYONLINECUSTOMGAME
registerVal1.UI_CP2LOBBYONLINE.backTarget = registerVal1.UI_MODESELECT
registerVal1.UI_CP2LOBBYONLINE.errTarget = registerVal1.UI_CP2LOBBYONLINE
registerVal1.UI_CP2LOBBYONLINEPUBLICGAME.backTarget = registerVal1.UI_CP2LOBBYONLINE
registerVal1.UI_CP2LOBBYONLINEPUBLICGAME.errTarget = registerVal1.UI_CP2LOBBYONLINE
registerVal1.UI_CP2LOBBYONLINECUSTOMGAME.backTarget = registerVal1.UI_CP2LOBBYONLINE
registerVal1.UI_CP2LOBBYONLINECUSTOMGAME.errTarget = registerVal1.UI_CP2LOBBYONLINECUSTOMGAME
registerVal1.UI_DOALOBBYLANGAME.backTarget = registerVal1.UI_MODESELECT
registerVal1.UI_DOALOBBYLANGAME.errTarget = registerVal1.UI_DOALOBBYLANGAME
registerVal1.UI_DOALOBBYLANCUSTOMGAME.backTarget = registerVal1.UI_DOALOBBYLANGAME
registerVal1.UI_DOALOBBYLANCUSTOMGAME.errTarget = registerVal1.UI_DOALOBBYLANGAME
registerVal1.UI_DOALOBBYONLINE.backTarget = registerVal1.UI_MODESELECT
registerVal1.UI_DOALOBBYONLINE.errTarget = registerVal1.UI_DOALOBBYONLINE
registerVal1.UI_DOALOBBYONLINEPUBLICGAME.backTarget = registerVal1.UI_DOALOBBYONLINE
registerVal1.UI_DOALOBBYONLINEPUBLICGAME.errTarget = registerVal1.UI_DOALOBBYONLINE
registerVal1.UI_MPLOBBYLANGAME.backTarget = registerVal1.UI_MODESELECT
registerVal1.UI_MPLOBBYLANGAME.errTarget = registerVal1.UI_MODESELECT
registerVal1.UI_MPLOBBYMAIN.backTarget = registerVal1.UI_MODESELECT
registerVal1.UI_MPLOBBYMAIN.errTarget = registerVal1.UI_MODESELECT
registerVal1.UI_MPLOBBYONLINE.backTarget = registerVal1.UI_MPLOBBYMAIN
registerVal1.UI_MPLOBBYONLINE.errTarget = registerVal1.UI_MPLOBBYONLINE
registerVal1.UI_MPLOBBYONLINEPUBLICGAME.backTarget = registerVal1.UI_MPLOBBYONLINE
registerVal1.UI_MPLOBBYONLINEPUBLICGAME.errTarget = registerVal1.UI_MPLOBBYONLINE
registerVal1.UI_MPLOBBYONLINEMODGAME.backTarget = registerVal1.UI_MPLOBBYMAIN
registerVal1.UI_MPLOBBYONLINEMODGAME.errTarget = registerVal1.UI_MPLOBBYMAIN
registerVal1.UI_MPLOBBYONLINECUSTOMGAME.backTarget = registerVal1.UI_MPLOBBYMAIN
registerVal1.UI_MPLOBBYONLINECUSTOMGAME.errTarget = registerVal1.UI_MPLOBBYONLINECUSTOMGAME
registerVal1.UI_MPLOBBYONLINETHEATER.backTarget = registerVal1.UI_MPLOBBYMAIN
registerVal1.UI_MPLOBBYONLINETHEATER.errTarget = registerVal1.UI_MPLOBBYONLINETHEATER
registerVal1.UI_MPLOBBYONLINEARENA.backTarget = registerVal1.UI_MPLOBBYMAIN
registerVal1.UI_MPLOBBYONLINEARENA.errTarget = registerVal1.UI_MPLOBBYMAIN
registerVal1.UI_MPLOBBYONLINEARENAGAME.backTarget = registerVal1.UI_MPLOBBYONLINEARENA
registerVal1.UI_MPLOBBYONLINEARENAGAME.errTarget = registerVal1.UI_MPLOBBYONLINEARENA
registerVal1.UI_ZMLOBBYLANGAME.backTarget = registerVal1.UI_MODESELECT
registerVal1.UI_ZMLOBBYLANGAME.errTarget = registerVal1.UI_ZMLOBBYLANGAME
registerVal1.UI_ZMLOBBYONLINE.backTarget = registerVal1.UI_MODESELECT
registerVal1.UI_ZMLOBBYONLINE.errTarget = registerVal1.UI_ZMLOBBYONLINE
registerVal1.UI_ZMLOBBYONLINEPUBLICGAME.backTarget = registerVal1.UI_ZMLOBBYONLINE
registerVal1.UI_ZMLOBBYONLINEPUBLICGAME.errTarget = registerVal1.UI_ZMLOBBYONLINE
registerVal1.UI_ZMLOBBYONLINECUSTOMGAME.backTarget = registerVal1.UI_ZMLOBBYONLINE
registerVal1.UI_ZMLOBBYONLINECUSTOMGAME.errTarget = registerVal1.UI_ZMLOBBYONLINECUSTOMGAME
registerVal1.UI_ZMLOBBYONLINETHEATER.backTarget = registerVal1.UI_ZMLOBBYONLINE
registerVal1.UI_ZMLOBBYONLINETHEATER.errTarget = registerVal1.UI_ZMLOBBYONLINETHEATER
registerVal1.UI_FRLOBBYONLINEGAME.backTarget = registerVal1.UI_MODESELECT
registerVal1.UI_FRLOBBYONLINEGAME.errTarget = registerVal1.UI_MODESELECT
registerVal1.UI_FRLOBBYLANGAME.backTarget = registerVal1.UI_MODESELECT
registerVal1.UI_FRLOBBYLANGAME.errTarget = registerVal1.UI_MODESELECT
{}.LobbyClosed = "uin_lobby_closed"
{}.ClientsAddedToLobby = "uin_lobby_enter"
{}.ClientsRemovedFromLobby = "uin_lobby_exit"
{}.TimerTick = "uin_timer"
{}.ESportsTimerTick = "uin_timer_esports_beep"
{}.ESportsTimerTickLast = "uin_timer_esports_last_beep"
local function __FUNC_4246_()
	local registerVal1 = Engine.GetGlobalModel()
	local registerVal0 = Engine.CreateModel(registerVal1, "lobbyRoot.lobbyNav", true)
	Engine.SetModelValue(registerVal0, {}.UITargets.UI_MAIN.id)
	local registerVal2 = Engine.GetGlobalModel()
	registerVal1 = Engine.CreateModel(registerVal2, "lobbyRoot.room", true)
	Engine.SetModelValue(registerVal1, "room1")
	if LUI then
		LUI.CoDMetrics.LobbyInit()
	end
end

{}.InitLobbyNav = __FUNC_4246_
function {}.GetLobbyNavModel()
	local registerVal1 = Engine.GetGlobalModel()
	return Engine.GetModel(registerVal1, "lobbyRoot.lobbyNav")
end

local function __FUNC_4502_()
	local registerVal0 = {}.GetLobbyNavModel()
	return Engine.GetModelValue(registerVal0)
end

{}.GetLobbyNav = __FUNC_4502_
function {}.GetCurrentMenuTarget()
	local registerVal0 = Engine.GetLobbyUIScreen()
	return LobbyData:UITargetFromId(registerVal0)
end

local function __FUNC_4645_(arg0)
	local registerVal1 = {}.GetLobbyNavModel()
	if not registerVal1 then
		{}.InitLobbyNav()
		local registerVal2 = {}.GetLobbyNavModel()
	end
	registerVal2 = Engine.GetModelValue(registerVal2)
	local registerVal6 = tostring(registerVal2)
	local registerVal8 = tostring(arg0.id)
	Engine.PrintInfo(Enum.consoleLabel.LABEL_LOBBY, ("LobbyData.SetLobbyNav. From: " .. registerVal6 .. " To: " .. registerVal8 .. "
"))
	Engine.SetModelValue(registerVal2, arg0.id)
	local registerVal4 = Engine.GetGlobalModel()
	local registerVal3 = Engine.CreateModel(registerVal4, "lobbyRoot.lobbyTitle")
	Engine.SetModelValue(registerVal3, arg0.title)
	local registerVal5 = Engine.GetGlobalModel()
	registerVal4 = Engine.CreateModel(registerVal5, "lobbyRoot.headingKickerMode")
	local registerVal7 = Engine.Localize(arg0.kicker)
	if arg0.kicker and arg0.kicker == "" or not registerVal7 then
	end
	Engine.SetModelValue(registerVal4, "")
	registerVal6 = Engine.GetGlobalModel()
	Engine.CreateModel(registerVal6, "lobbyRoot.headingKickerText")
end

{}.SetLobbyNav = __FUNC_4645_
function {}.UITargetFromName(arg0, arg1)
	local registerVal3, registerVal4, registerVal5 = pairs(arg0.UITargets._originalTable)
	for index6,value7 in registerVal3, registerVal4, registerVal5 do
		if value7.name == arg1 then
			return value7
		end
	end
	print(("Lobby VM: No valid ui target found for menu name: " .. arg1))
	return nil
end

function {}.UITargetFromId(arg0, arg1)
	local registerVal3, registerVal4, registerVal5 = pairs(arg0.UITargets._originalTable)
	for index6,value7 in registerVal3, registerVal4, registerVal5 do
		if value7.id == arg1 then
			return value7
		end
	end
	print(("Lobby VM: No valid ui target found for menu id: " .. nil))
	return nil
end

function {}.PartyPrivacyToString(arg0)
	if arg0 == Enum.PartyPrivacy.PARTY_PRIVACY_OPEN then
	else
		if arg0 == Enum.PartyPrivacy.PARTY_PRIVACY_FRIENDS_ONLY then
		else
			if arg0 == Enum.PartyPrivacy.PARTY_PRIVACY_INVITE_ONLY then
			else
				if arg0 == Enum.PartyPrivacy.PARTY_PRIVACY_CLOSED then
				end
			end
		end
	end
	return Engine.Localize("MENU_PARTY_PRIVACY_CLOSED")
end

local registerVal3 = {}
local registerVal4 = {}
registerVal4.name = "SceaEnFr"
local registerVal5 = {}
registerVal5 = {"en", "fr"}
registerVal4.langs = registerVal5
registerVal4.region = 0.000000
registerVal5 = {}
registerVal5.name = "SceaMsEn"
local registerVal6 = {}
registerVal6 = {"ms", "en"}
registerVal5.langs = registerVal6
registerVal5.region = 0.000000
registerVal6 = {}
registerVal6.name = "SceaBpEn"
local registerVal7 = {}
registerVal7 = {"bp", "en", "tc", "sc"}
registerVal6.langs = registerVal7
registerVal6.region = 0.000000
registerVal7 = {}
registerVal7.name = "SceeEnFr"
local registerVal8 = {}
registerVal8 = {"en", "fr"}
registerVal7.langs = registerVal8
registerVal7.region = 1.000000
registerVal8 = {}
registerVal8.name = "SceeGeEn"
local registerVal9 = {}
registerVal9 = {"ge", "en"}
registerVal8.langs = registerVal9
registerVal8.region = 1.000000
registerVal9 = {}
registerVal9.name = "SceeSpIt"
local registerVal10 = {}
registerVal10 = {"es", "it"}
registerVal9.langs = registerVal10
registerVal9.region = 1.000000
registerVal10 = {}
registerVal10.name = "SceeRuPo"
local registerVal11 = {}
registerVal11 = {"ru", "po"}
registerVal10.langs = registerVal11
registerVal10.region = 1.000000
registerVal11 = {}
registerVal11.name = "SceeArEa"
local registerVal12 = {}
registerVal12 = {"ar", "ea"}
registerVal11.langs = registerVal12
registerVal11.region = 1.000000
registerVal12 = {}
registerVal12.name = "ScejFjJa"
local registerVal13 = {}
registerVal13 = {"fj", "ja"}
registerVal12.langs = registerVal13
registerVal12.region = 2.000000
registerVal3 = {registerVal4, registerVal5, registerVal6, registerVal7, registerVal8, registerVal9, registerVal10, registerVal11, registerVal12}
{}.PS4SkuList = registerVal3
registerVal3 = {}
registerVal4 = {}
registerVal4.name = "XboxEnFr"
registerVal5 = {}
registerVal5 = {"en", "fr"}
registerVal4.langs = registerVal5
registerVal4.region = 0.000000
registerVal5 = {}
registerVal5.name = "XboxMsEn"
registerVal6 = {}
registerVal6 = {"ms", "en"}
registerVal5.langs = registerVal6
registerVal5.region = 0.000000
registerVal6 = {}
registerVal6.name = "XboxBpEn"
registerVal7 = {}
registerVal7 = {"bp", "en", "tc", "sc"}
registerVal6.langs = registerVal7
registerVal6.region = 0.000000
registerVal7 = {}
registerVal7.name = "XboxGeEn"
registerVal8 = {}
registerVal8 = {"ge", "en"}
registerVal7.langs = registerVal8
registerVal7.region = 0.000000
registerVal8 = {}
registerVal8.name = "XboxSpIt"
registerVal9 = {}
registerVal9 = {"es", "it"}
registerVal8.langs = registerVal9
registerVal8.region = 0.000000
registerVal9 = {}
registerVal9.name = "XboxRuPo"
registerVal10 = {}
registerVal10 = {"ru", "po"}
registerVal9.langs = registerVal10
registerVal9.region = 0.000000
registerVal10 = {}
registerVal10.name = "XboxArEa"
registerVal11 = {}
registerVal11 = {"ar", "ea"}
registerVal10.langs = registerVal11
registerVal10.region = 0.000000
registerVal11 = {}
registerVal11.name = "XboxFjJa"
registerVal12 = {}
registerVal12 = {"fj", "ja"}
registerVal11.langs = registerVal12
registerVal11.region = 0.000000
registerVal12 = {}
registerVal12.name = "XboxInvalid"
registerVal13 = {}
registerVal13 = {"en", "fr", "it", "de", "pt", "pl", "ru", "ja", "es", "zm"}
registerVal12.langs = registerVal13
registerVal12.region = 0.000000
registerVal3 = {registerVal4, registerVal5, registerVal6, registerVal7, registerVal8, registerVal9, registerVal10, registerVal11, registerVal12}
{}.XBOXSkuList = registerVal3
registerVal3, registerVal4, registerVal5 = ipairs({}.PS4SkuList)
for index6,value7 in registerVal3, registerVal4, registerVal5 do
	table["sort"](value7.langs)
end
registerVal3, registerVal4, registerVal5 = ipairs({}.XBOXSkuList)
for index6,value7 in registerVal3, registerVal4, registerVal5 do
	table["sort"](value7.langs)
end
local function __FUNC_4EF8_()
	local registerVal1 = Engine.GetGlobalModel()
	local registerVal0 = Engine.GetModel(registerVal1, "ButtonStates.ReevaluateDisabledStates")
	if registerVal0 then
		registerVal1 = Engine.GetModelValue(registerVal0)
		Engine.SetModelValue(registerVal0, (not registerVal0))
	end
end

{}["ButtonStates_ReevaluateDisabledState"] = __FUNC_4EF8_
registerVal4 = LuaReadOnlyTables["ReadOnlyTable"]({})
{}["Sounds"] = registerVal4
registerVal4 = LuaReadOnlyTables["ReadOnlyTable"](registerVal1)
{}["UITargets"] = registerVal4
registerVal3 = LuaReadOnlyTables["ReadOnlyTable"]({})
LobbyData = registerVal3
